# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "MM_Bow_Aiming_Reticle"

# Version of this mod.
version = "1.0.3"

# Authors of this mod.
authors = [ "LT_Schmiddy" ]

display_name = "Bow Aiming Reticle"

# ID of the target recomp game.
game_id = "mm"

description =  """
A simple QOL mod. Draws an aiming reticle when the bow is out and an arrow is drawn.
"""
short_description = "Draws an aiming reticle when aiming the bow with an arrow drawn."
# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

mod_filename = "MM_Bow_Aiming_Reticle"


# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]
